/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'icon' : string,
  'name' : string,
  'products' : Array<Product>,
}
export interface Contact {
  'date' : Time,
  'name' : string,
  'message' : string,
  'phone' : string,
}
export interface Product {
  'name' : string,
  'unit' : string,
  'emoji' : string,
  'price' : bigint,
}
export interface Review {
  'date' : Time,
  'name' : string,
  'comment' : string,
  'rating' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'addReview' : ActorMethod<[string, bigint, string], undefined>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getContacts' : ActorMethod<[], Array<Contact>>,
  'getReviews' : ActorMethod<[], Array<Review>>,
  'getStoreInfo' : ActorMethod<
    [],
    {
      'storeInfo' : {
        'tagline' : string,
        'name' : string,
        'address' : string,
        'phone' : string,
      },
    }
  >,
  'submitContact' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];