/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'emoji' : IDL.Text,
  'price' : IDL.Nat,
});
export const Category = IDL.Record({
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'products' : IDL.Vec(Product),
});
export const Time = IDL.Int;
export const Contact = IDL.Record({
  'date' : Time,
  'name' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const Review = IDL.Record({
  'date' : Time,
  'name' : IDL.Text,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getStoreInfo' : IDL.Func(
      [],
      [
        IDL.Record({
          'storeInfo' : IDL.Record({
            'tagline' : IDL.Text,
            'name' : IDL.Text,
            'address' : IDL.Text,
            'phone' : IDL.Text,
          }),
        }),
      ],
      ['query'],
    ),
  'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'emoji' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Category = IDL.Record({
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'products' : IDL.Vec(Product),
  });
  const Time = IDL.Int;
  const Contact = IDL.Record({
    'date' : Time,
    'name' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Review = IDL.Record({
    'date' : Time,
    'name' : IDL.Text,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'addReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getStoreInfo' : IDL.Func(
        [],
        [
          IDL.Record({
            'storeInfo' : IDL.Record({
              'tagline' : IDL.Text,
              'name' : IDL.Text,
              'address' : IDL.Text,
              'phone' : IDL.Text,
            }),
          }),
        ],
        ['query'],
      ),
    'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };